package edu.cmu.cs.sasylf.ast;

import edu.cmu.cs.sasylf.interactive.Orchestrator;
import edu.cmu.cs.sasylf.module.Module;
import edu.cmu.cs.sasylf.module.ModuleFinder;
import edu.cmu.cs.sasylf.module.ModuleId;
import edu.cmu.cs.sasylf.module.NullModuleFinder;
import edu.cmu.cs.sasylf.parser.ParseException;
import edu.cmu.cs.sasylf.parser.Token;
import edu.cmu.cs.sasylf.util.*;

import java.io.PrintWriter;
import java.util.*;
import java.util.function.Consumer;


public class CompUnit extends Node implements Module {

    private Context ctxt;
    private PackageDeclaration packageDecl;
    private String moduleName;
    private List<Part> params = new ArrayList<Part>();
    private List<Part> parts = new ArrayList<Part>();
    private int parseReports;
    private Map<String, Object> declCache = new HashMap<String, Object>();
    private int cacheVersion = -1;

    public CompUnit(PackageDeclaration pack, Location loc, String n) {
        super(loc);
        packageDecl = pack;
        moduleName = n;
        updateReportCount();
    }

    public Context getContext() {
        return ctxt;
    }

    /**
     * Update the number of reports generated during parsing.
     */
    protected void updateReportCount() {
        parseReports = ErrorHandler.getReports().size();
    }

    /**
     * Add a chunk that is required by this module.
     *
     * @param c part to add, must not be null
     */
    public void addParameterChunk(Part c) {
        params.add(c);
        updateReportCount();
    }

    /**
     * Add a part to this compilation unit.
     *
     * @param c
     */
    public void addChunk(Part c) {
        parts.add(c);
        updateReportCount();
    }

    public PackageDeclaration getPackage() {
        return packageDecl;
    }

    /* (non-Javadoc)
     * @see edu.cmu.cs.sasylf.ast.Module#getName()
     */
    @Override
    public String getName() {
        return moduleName;
    }

    @Override
    public boolean isAbstract() {
        return !params.isEmpty();
    }

    /* (non-Javadoc)
     * @see edu.cmu.cs.sasylf.ast.Module#prettyPrint(java.io.PrintWriter)
     */
    @Override
    public void prettyPrint(PrintWriter out) {
        packageDecl.prettyPrint(out);

        if (moduleName != null) {
            out.println("module " + moduleName);
        }

        if (!params.isEmpty()) {
            out.println("requires");
            for (Part part : params) {
                part.prettyPrint(out);
            }
            out.println("provides");
        }

        for (Part part : parts) {
            part.prettyPrint(out);
        }

        out.flush();
    }

    /**
     * Return the number of reports generated by the parser before this
     * compilation unit was generated.
     *
     * @return number of errors
     */
    public int getParseReports() {
        return parseReports;
    }

    /* (non-Javadoc)
     * @see edu.cmu.cs.sasylf.ast.Module#typecheck()
     */
    @Override
    public boolean typecheck() {
        return typecheck(NullModuleFinder.get(), (ModuleId) null);
    }

    /**
     * Typechecks this compilation unit, returning true if the check was successful,
     * false if there were one or more errors.
     */
    public boolean typecheck(ModuleFinder mf, ModuleId id) {
        ErrorHandler.recordLastSpan(this);
        int oldCount = ErrorHandler.getErrorCount();
        this.ctxt = new Context(mf, this);
        try {
            typecheck(ctxt, id);
        } catch (SASyLFError e) {
            // ignore the error; it has already been reported
            //e.printStackTrace();
        }
        return ErrorHandler.getErrorCount() == oldCount;
    }

    /**
     * Typechecks this compilation unit, returning true if the check was successful,
     * false if there were one or more errors.
     */
    public boolean run(Orchestrator orch, ModuleFinder mf, ModuleId id) {
        ErrorHandler.recordLastSpan(this);
        int oldCount = ErrorHandler.getErrorCount();
        this.ctxt = new Context(mf, this);
        try {
            var moduleDelegate = new Orchestrator.Delegate<>(parser -> parser.ModulePartInteractive(false)) {
                @Override
                public void run(Context ctx, Part part) throws ParseException {
                    addChunk(part);
                    typecheck();
                }
            };

            var thmPrologDelegate = new Orchestrator.Delegate<>(parser ->
                    parser.TheoremPrologue(false)
            ) {
                @Override
                public void run(Context ctx, Pair<Theorem, Token> pair) {
                    ctxt = pair.first.run(orch, ctx, pair.second);
                    List<Theorem> theorems = new ArrayList<>();
                    theorems.add(pair.first);
                    var part = new TheoremPart(theorems);
                    addChunk(part);
                    typecheck();
                }
            };

            var partDelegate = new Orchestrator.Delegate<>(parser ->
                    parser.PartInteractive(false)
            ) {
                @Override
                public void run(Context ctx, Part part) {
                    addChunk(part);
                    typecheck();
                }
            };

            orch.runNextNode(
                    this.ctxt,
                    moduleDelegate,
                    thmPrologDelegate,
                    partDelegate
            );

            while (true) {
                orch.runNextNode(
                        this.ctxt,
                        thmPrologDelegate,
                        partDelegate
                );
            }
        } catch (SASyLFError e) {
            // ignore the error; it has already been reported
            //e.printStackTrace();
        }
        return ErrorHandler.getErrorCount() == oldCount;
    }

    /**
     * Check this compilation unit in the given context.
     *
     * @param ctx context, must not be null
     * @param id  identifier declared for this compilation unit, or null if no declared module name
     */
    public void typecheck(Context ctx, ModuleId id) {
        if (id != null) checkFilename(id);
        for (Part part : params) {
            try {
                part.typecheck(ctx);
                if (part instanceof JudgmentPart) {
                    List<Node> pieces = new ArrayList<>();
                    part.collectTopLevel(pieces);
                    for (Node n : pieces) {
                        if (n instanceof Judgment) {
                            Judgment j = (Judgment) n;
                            if (!j.isAbstract() && j.getRules().isEmpty()) {
                                ErrorHandler.recoverableError(Errors.ABSTRACT_REQUIRED, j);
                            }
                        }
                    }
                }
            } catch (SASyLFError ex) {
                // already reported
            }
        }
        for (Part part : parts) {
            try {
                part.typecheck(ctx);
            } catch (SASyLFError ex) {
                // already reported
            }
        }
    }

    private void checkFilename(ModuleId id) {
        packageDecl.typecheck(id.packageName);

        if (moduleName != null) {
            if (!ParseUtil.isLegalIdentifier(id.moduleName)) {
                ErrorHandler.error(Errors.BAD_FILE_NAME, this);
            }
            if (!moduleName.equals(id.moduleName)) {
                ErrorHandler.warning(Errors.WRONG_MODULE_NAME, this, moduleName + "\n" + id.moduleName);
            }
        }
    }

    /* (non-Javadoc)
     * @see edu.cmu.cs.sasylf.ast.Module#collectTopLevel(java.util.Collection)
     */
    @Override
    public void collectTopLevel(Collection<? super Node> things) {
        for (Part part : params) {
            part.collectTopLevel(things);
        }
        for (Part part : parts) {
            part.collectTopLevel(things);
        }
    }

    /* (non-Javadoc)
     * @see edu.cmu.cs.sasylf.ast.Module#collectRuleLike(java.util.Map)
     */
    @Override
    public void collectRuleLike(Map<String, ? super RuleLike> map) {
        for (Part part : params) {
            part.collectRuleLike(map);
        }
        for (Part part : parts) {
            part.collectRuleLike(map);
        }
    }

    /**
     * Collect all {@link QualName}s using the given consumer.
     *
     * @param consumer The consumer that accepts conditions based on the given {@link QualName}.
     */
    @Override
    public void collectQualNames(Consumer<QualName> consumer) {
        for (Part part : params) {
            part.collectQualNames(consumer);
        }

        for (Part part : parts) {
            part.collectQualNames(consumer);
        }
    }

    @Override
    public Object getDeclaration(Context ctx, String name) {
        if (cacheVersion != ctx.version()) {
            declCache.clear();
            Collection<Node> things = new ArrayList<Node>();
            this.collectTopLevel(things);
            this.collectRuleLike(declCache); // doesn't get syntax declarations or judgments
            for (Node n : things) {
                if (n instanceof SyntaxDeclaration) {
                    SyntaxDeclaration sd = (SyntaxDeclaration) n;
                    for (String s : sd.getAlternates()) {
                        declCache.put(s, sd);
                    }
                } else if (n instanceof Judgment) {
                    Judgment jd = (Judgment) n;
                    declCache.put(jd.getName(), jd);
                }
            }
            cacheVersion = ctx.version();
        }
        return declCache.get(name);
    }
}
